@startuml
interface ControllableGameModel {
~ ControllableLevel getControllableLevel()
~ void setState(GameState)
~ void setLevel(String)
}

class TileGrassCornerRight1 {
+ {static} char KEY
+ <<Create>> TileGrassCornerRight1(World,EventBus,float,float)
}


abstract class DoorModel {
- EventBus eventBus
# <<Create>> DoorModel(World,EventBus,float,float,float,float)
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
}


interface GameStateGettable {
~ GameState getState()
}

abstract class Effect {
- float speedBoost
- float jumpBoost
- int maxDuration
- int duration
+ <<Create>> Effect(int,float,float)
+ void step()
+ boolean hasEnded()
+ float getSpeedBoost()
+ float getJumpBoost()
+ Durability getDuration()
}


class TileGroundLeft {
+ {static} char KEY
+ <<Create>> TileGroundLeft(World,EventBus,float,float)
}


class ItemHP {
- {static} int DURABILITY
- {static} int DURATION
+ <<Create>> ItemHP(EventBus,World,float,float)
+ String getDescription()
+ String getName()
}


class PauseScreen {
- Texture texture
- String title
- String text
- GlyphLayout titleLayout
- GlyphLayout textLayout
+ <<Create>> PauseScreen(InputProcessor)
+ void render(float)
}


class Controller {
- ControllableGameModel model
- boolean wasMenu
+ <<Create>> Controller(ControllableGameModel)
+ boolean keyDown(int)
- void chooseLevel(int)
+ boolean keyUp(int)
+ void handleEvent(Event)
}


class TileFloatingGround {
+ {static} char KEY
+ <<Create>> TileFloatingGround(World,EventBus,float,float)
}


class TileMiddle {
+ {static} char KEY
+ <<Create>> TileMiddle(World,EventBus,float,float)
}


class EventBus {
- List<EventHandler> handlers
+ <<Create>> EventBus()
+ void post(Event)
+ void addEventHandler(EventHandler)
+ void removeEventHandler(EventHandler)
}


class InfoScreen {
- {static} Texture texture
- Table tableController
- Table tableItem
- Stage stage
- Label.LabelStyle labelStyle
- ITexturePack texturePack
- ItemMushroom itemMushroom
- ItemEnergy itemEnergy
- Image mushroomImg
- Image energyImg
- ItemHP itemHp
- Image hpImg
+ <<Create>> InfoScreen(InputProcessor)
- void createLeftTable()
- void createRightTable()
- void createItemGroup(Image,ViewableItem)
- void createDescriptionContainer(ViewableItem)
+ void render(float)
}


class TileGround {
+ {static} char KEY
+ <<Create>> TileGround(World,EventBus,float,float)
}


class Hud {
- {static} int IMG_SIZE
- {static} int TEXT_WIDTH
- {static} int TEXT_HEIGHT
- ViewableLevel level
- ITexturePack texturePack
- Image itemIcon
- Label itemDurability
- HorizontalGroup effectIcons
- Map<ViewableEffect,Image> effectIconImages
- HorizontalGroup effectDurations
- Map<ViewableEffect,Image> effectDurationImages
- Table table
- HorizontalGroup hpGroup
- LinkedList<Image> hpIcons
+ <<Create>> Hud(SpriteBatch,ViewableLevel,ITexturePack)
- void fillTable()
- void updateHp()
- void drawHp()
- void updateItemActors()
- void updateEffectActors()
- Sprite getEffectDuration(ViewableEffect)
- void update()
+ void draw()
}


class TexturePack {
+ {static} String TILE_NAME
- {static} TextureAtlas atlas
- {static} int TILE_WIDTH
- {static} int TILE_HEIGHT
- {static} Map<PlayerState,Animation<TextureRegion>> PLAYER_ANIMATION_MAP
- float playerStateTime
- PlayerState playerLastState
- {static} Animation<TextureRegion> loadAnimation(String,int)
- TextureRegion getTextureFromAtlas(int)
+ TextureRegion getTileTexture(ViewableTile)
+ TextureRegion getPlayerTexture(PlayerState,float)
- void updatePlayerVariables(PlayerState,float)
+ TextureRegion getItemTexture(ViewableItem)
+ TextureRegion getHpTexture()
+ TextureRegion getEffectTexture(ViewableEffect)
+ TextureRegion getInventorySlot()
}


class TileFloatingGroundLeftSlim {
+ {static} char KEY
+ <<Create>> TileFloatingGroundLeftSlim(World,EventBus,float,float)
}


class TileGrassCornerRight2 {
+ {static} char KEY
+ <<Create>> TileGrassCornerRight2(World,EventBus,float,float)
}


class MenuScreen {
- {static} float TEXTURE_RATIO
- {static} Texture texture
- {static} String title
- {static} String text
- {static} GlyphLayout titleLayout
- {static} GlyphLayout textLayout
+ <<Create>> MenuScreen(InputProcessor)
+ void render(float)
}


class ItemEnergy {
- {static} int DURABILITY
- {static} int DURATION
+ <<Create>> ItemEnergy(EventBus,World,float,float)
+ String getDescription()
+ String getName()
}


class Saw {
+ {static} char KEY
- {static} int DAMAGE
+ <<Create>> Saw(World,EventBus,float,float)
+ <<Create>> Saw(World,EventBus,float,float,float)
# Shape createShape(float,float)
# Body createBody(float,float)
+ float getY()
}


abstract class DamageTileModel {
- int DAMAGE
- EventBus eventBus
# <<Create>> DamageTileModel(World,EventBus,float,float,float,float,int)
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
}


interface ViewableTile {
}
class Health {
- Object owner
- EventBus bus
- int max
- int health
+ <<Create>> Health(Object,EventBus,int)
+ <<Create>> Health(Object,EventBus,int,int)
+ void regenerate(int)
+ void damage(int)
+ int getHealth()
+ int getMaxHealth()
}


interface Positionable {
~ float getX()
~ float getY()
}

class VictoryScreen {
- Texture texture
- GlyphLayout textLayout
- GlyphLayout titleLayout
- String text
- String title
+ <<Create>> VictoryScreen(InputProcessor)
+ void render(float)
}


class Main {
+ {static} void main(String[])
}

class LevelScreen {
- Texture texture
- Table table
- Label.LabelStyle labelStyle
- String title
- Stage stage
+ <<Create>> LevelScreen(InputProcessor)
- void createLevelTable()
+ void render(float)
}


class Door2 {
+ {static} char KEY
+ <<Create>> Door2(World,EventBus,float,float)
+ <<Create>> Door2(World,EventBus,float,float,float,float)
}


class ContactListeners {
- List<ContactListener> contactListeners
+ <<Create>> ContactListeners()
+ boolean add(ContactListener)
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
}


class EventStep {
- float timeStep
+ <<Create>> EventStep(float)
+ float timeStep()
}


class TileGrassCornerLeft2 {
+ {static} char KEY
+ <<Create>> TileGrassCornerLeft2(World,EventBus,float,float)
}


class EffectHpUp {
- {static} float SPEED_BOOST
- {static} float JUMP_BOOST
+ <<Create>> EffectHpUp(int)
}


class EventReachedDoor {
+ <<Create>> EventReachedDoor()
}

class EventLevelChanged {
+ <<Create>> EventLevelChanged()
}

class GameScreen {
- {static} float VIEWPORT_WIDTH
- {static} float VIEWPORT_HEIGHT
- EventBus eventBus
- ViewableLevel level
- OrthographicCamera gameCam
- Viewport gamePort
- SpriteBatch batch
- SpriteBatch batchHud
- ITexturePack texturePack
- Stage hud
- Stage BackgroundLayers
+ <<Create>> GameScreen(ViewableLevel,EventBus,InputProcessor)
+ void show()
+ void render(float)
- void updateCamToPlayer()
- void renderTiles(List<ViewableTile>,float)
- void renderTile(ViewableTile,float)
- void renderItems()
- void renderItem(ViewableItem)
- void addBackgroundLayers(Array<Texture>)
+ void dispose()
+ void resize(int,int)
+ void pause()
+ void resume()
+ void hide()
}


class EventItemPickedUp {
- ItemModel item
+ <<Create>> EventItemPickedUp(ItemModel)
+ ItemModel item()
}


interface Sizeable {
~ float getWidth()
~ float getHeight()
}

class EventDamage {
- int damage
- Fixture fixture
+ <<Create>> EventDamage(int,Fixture)
+ Fixture fixture()
+ int damage()
}


class PlayerModel {
- {static} String USERDATA_BOTTOM
- {static} String USERDATA_LEFT
- {static} String USERDATA_RIGHT
- {static} String USERDATA_TOP
- {static} String USERDATA_SENSOR
- {static} float WIDTH
- {static} float HEIGHT
- {static} float DX
- {static} float DY
- {static} float AIR_CONTROL
- {static} float MAX_DX
- {static} float MAX_DY
- {static} float DENSITY
- {static} float FRICTION
- {static} float FRICTION_BOTTOM
- {static} float RESTITUTION
- {static} Set<Object> USERDATA_SET
- EventBus bus
- World world
- float void_height
- Body body
- List<Effect> effects
- IHealth hp
- Shape shapeTop
- Shape shapeSensor
- PlayerState state
- boolean moveUp
- int contactCountSensor
- ItemModel item
- float immunityCoolDown
+ <<Create>> PlayerModel(EventBus,World,float,float)
+ <<Create>> PlayerModel(EventBus,World,float,float,float)
- {static} HashSet<Object> createUserDataSet()
- boolean isContacted(Fixture)
+ void moveUp(boolean)
+ void moveDown(boolean)
+ void moveLeft(boolean)
+ void moveRight(boolean)
+ void useItem()
+ float getX()
+ float getY()
+ float getWidth()
+ float getHeight()
+ void step(float)
- boolean isGrounded()
- void move(float,float)
- Body createBody(float,float)
- void createShapes()
- void createFixtures(Body)
+ void handleEvent(Event)
- void handleDamage(int)
+ PlayerState getState()
- void updateState()
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
- boolean isSensorToGroundContact(Contact)
- boolean isBottomToGroundContact(Contact)
+ int getHp()
+ List<ViewableEffect> getEffects()
+ ViewableItem getItem()
}


class GameView {
+ {static} float VIEWPORT_WIDTH
+ {static} float VIEWPORT_HEIGHT
+ {static} float ASPECT_RATIO
- EventBus bus
- InputProcessor processor
- IAssetsManager assetsManager
- ViewableGameModel model
+ <<Create>> GameView(ViewableGameModel,EventBus,InputProcessor)
+ void create()
- void updateScreenAndMusic(GameState)
+ void handleEvent(Event)
}


interface EventHandler {
~ void handleEvent(Event)
}

abstract class TileHalf {
+ <<Create>> TileHalf(World,float,float,float,float)
+ <<Create>> TileHalf(World,EventBus,float,float)
# Shape createShape(float,float)
}

class TileGroundRight {
+ {static} char KEY
+ <<Create>> TileGroundRight(World,EventBus,float,float)
}


class Level {
- {static} int VELOCITY_ITERATIONS
- {static} int POSITION_ITERATIONS
+ float void_height
- EventBus bus
- float gravity
- float wind
- String default_foreground
- String default_background
- List<Function<World,ItemModel>> default_items
- float default_player_x
- float default_player_y
- World world
- List<TileModel> foreground
- List<TileModel> background
- List<ItemModel> items
- PlayerModel player
- List<ItemModel> toBeRemoved
- boolean isActive
- boolean initialized
+ <<Create>> Level(EventBus,float,float,float,float,float,String,String,List<Function<World,ItemModel>>)
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
+ void handleEvent(Event)
+ void step(float)
+ ControllablePlayerModel getControllablePlayer()
- void removeEventHandlers()
- void addEventHandlers()
- void disposeContents()
+ void reset()
+ void activate()
+ void disable()
+ ViewablePlayerModel getViewablePlayer()
+ List<ViewableTile> getForegroundTiles()
+ List<ViewableTile> getBackgroundTiles()
+ List<ViewableItem> getItems()
}


class EventItemUsedUp {
- ItemModel item
+ <<Create>> EventItemUsedUp(ItemModel)
+ ItemModel item()
}


class GameModel {
- EventBus bus
- Map<String,ILevel> levels
- String level
- GameState state
+ <<Create>> GameModel(EventBus)
- void fillLevels()
+ GameState getState()
+ void setState(GameState)
+ ControllableLevel getControllableLevel()
+ void setLevel(String)
+ void handleEvent(Event)
+ ViewableLevel getViewableLevel()
}


class EffectSpeedBoost {
- {static} float SPEED_BOOST
- {static} float JUMP_BOOST
+ <<Create>> EffectSpeedBoost(int)
}


class TilePillar {
+ {static} char KEY
+ <<Create>> TilePillar(World,EventBus,float,float)
}


class Background {
- Array<Texture> layers
- float x
+ <<Create>> Background(Array<Texture>)
+ void draw(Batch,float)
}


class TileFloatingGroundRight {
+ {static} char KEY
+ <<Create>> TileFloatingGroundRight(World,EventBus,float,float)
}


abstract class TileModel {
+ {static} float TILE_WIDTH
+ {static} float TILE_HEIGHT
# World world
# Body body
# Shape shape
- float width
- float height
+ <<Create>> TileModel(World,EventBus,float,float)
+ <<Create>> TileModel(World,float,float,float,float)
# Body createBody(float,float)
# Shape createShape(float,float)
+ float getX()
+ float getY()
+ float getWidth()
+ float getHeight()
+ void step(float)
+ void handleEvent(Event)
}


interface ControllableLevel {
~ ControllablePlayerModel getControllablePlayer()
~ void reset()
~ void activate()
~ void disable()
}

interface Stepable {
~ void step(float)
}

enum PlayerState {
+  LEFT
+  RIGHT
+  JUMP_RIGHT
+  JUMP_LEFT
+  IDLE_RIGHT
+  IDLE_LEFT
}

abstract class AbstractScreen {
# {static} BitmapFont font
- {static} float ViewPort
+ {static} float VIEWPORT_WIDTH
+ {static} float VIEWPORT_HEIGHT
# SpriteBatch batch
# OrthographicCamera gameCam
- Viewport gamePort
+ <<Create>> AbstractScreen(InputProcessor)
+ void show()
- void update()
+ void render(float)
+ void resize(int,int)
+ void pause()
+ void resume()
+ void hide()
+ void dispose()
}


class Durability {
- int remaining
- int maximum
+ <<Create>> Durability(int,int)
+ int remaining()
+ int maximum()
}


class GameOverScreen {
- Texture texture
- GlyphLayout layout
- String title
- String text
+ <<Create>> GameOverScreen(InputProcessor)
+ void render(float)
}


class TileSideRight {
+ {static} char KEY
+ <<Create>> TileSideRight(World,EventBus,float,float)
}


interface ViewableItem {
~ String getDescription()
~ String getName()
~ Durability getDurability()
}

class EventGameState {
- GameState gameState
+ <<Create>> EventGameState(GameState)
+ GameState gameState()
}


abstract class ItemModel {
- {static} float WIDTH
- {static} float HEIGHT
- Body body
- World world
- EventBus bus
# Durability durability
# Supplier<Effect> createEffect
- Shape shape
+ <<Create>> ItemModel(EventBus,World,float,float)
- Body createBody(World,float,float)
+ Effect use()
- void reduceDurability()
+ void destroyBody()
+ float getWidth()
+ float getHeight()
+ float getX()
+ float getY()
+ Durability getDurability()
+ void handleEvent(Event)
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
- boolean isContacted(Contact)
}


interface ViewableEffect {
~ Durability getDuration()
}

class TileGroundSingle {
+ {static} char KEY
+ <<Create>> TileGroundSingle(World,EventBus,float,float)
}


interface IHealth {
~ void regenerate(int)
~ void damage(int)
~ int getHealth()
~ int getMaxHealth()
}

class EffectJumpBoost {
- {static} float SPEED_BOOST
- {static} float JUMP_BOOST
+ <<Create>> EffectJumpBoost(int)
}


class TileFloatingGroundLeft {
+ {static} char KEY
+ <<Create>> TileFloatingGroundLeft(World,EventBus,float,float)
}


class TileBottom {
+ {static} char KEY
+ <<Create>> TileBottom(World,EventBus,float,float)
}


interface ControllablePlayerModel {
~ void moveUp(boolean)
~ void moveDown(boolean)
~ void moveLeft(boolean)
~ void moveRight(boolean)
~ void useItem()
}

interface PlayerStateGettable {
~ PlayerState getState()
}

class TileBottomRight {
+ {static} char KEY
+ <<Create>> TileBottomRight(World,EventBus,float,float)
}


class ItemMushroom {
- {static} int DURABILITY
- {static} int DURATION
+ <<Create>> ItemMushroom(EventBus,World,float,float)
+ String getDescription()
+ String getName()
}


class TileFloatingGroundRightSlim {
+ {static} char KEY
+ <<Create>> TileFloatingGroundRightSlim(World,EventBus,float,float)
}


interface ContactableTiles {
}
class EventDispose {
}
class TileBottomLeft {
+ {static} char KEY
+ <<Create>> TileBottomLeft(World,EventBus,float,float)
}


class TileFloatingGroundSingle {
+ {static} char KEY
+ <<Create>> TileFloatingGroundSingle(World,EventBus,float,float)
}


interface Event {
}
class EventDeath {
- Object owner
+ <<Create>> EventDeath(Object)
+ Object owner()
}


interface ILevel {
}
class Spike {
+ {static} char KEY
- {static} int DAMAGE
+ <<Create>> Spike(World,EventBus,float,float)
+ <<Create>> Spike(World,EventBus,float,float,float,float)
# Shape createShape(float,float)
}


interface ViewableGameModel {
~ ViewableLevel getViewableLevel()
}

class TileFloatingGroundSingleSlim {
+ {static} char KEY
+ <<Create>> TileFloatingGroundSingleSlim(World,EventBus,float,float)
}


enum GameState {
+  MAIN_MENU
+  ACTIVE
+  GAME_OVER
+  PAUSE
+  VICTORY
+  INFO
+  LEVEL
}

class TileSideLeft {
+ {static} char KEY
+ <<Create>> TileSideLeft(World,EventBus,float,float)
}


class TileFloatingGroundSlim {
+ {static} char KEY
+ <<Create>> TileFloatingGroundSlim(World,EventBus,float,float)
}


interface ViewableLevel {
~ ViewablePlayerModel getViewablePlayer()
~ List<ViewableTile> getForegroundTiles()
~ List<ViewableTile> getBackgroundTiles()
~ List<ViewableItem> getItems()
}

class EventItemContact {
- Contact contact
- ItemModel item
+ <<Create>> EventItemContact(Contact,ItemModel)
+ Contact contact()
+ ItemModel item()
}


enum PlayerAction {
+  JUMP
+  PICKUP
+  DAMAGE
}

class TileFactory {
+ {static} Map<Character,Function4<World,EventBus,Float,Float,TileModel>> translation
+ {static} List<TileModel> generate(String,World,EventBus)
+ {static} void register(char,Function4<World,EventBus,Float,Float,TileModel>)
+ {static} void initialize()
}


interface IAssetsManager {
~ void playMusic(String)
~ void stopMusic()
~ void pauseMusic()
~ void resumeMusic()
~ void playSoundEffect(PlayerAction)
}

class AssetsManager {
- {static} Map<PlayerAction,String> soundEffectMap
- {static} Map<String,String> musicMap
- Map<PlayerAction,Sound> currentEffects
- Music nowPlaying
- String lastPlayed
+ <<Create>> AssetsManager()
+ void playMusic(String)
+ void stopMusic()
+ void pauseMusic()
+ void resumeMusic()
+ void playSoundEffect(PlayerAction)
}


interface ViewablePlayerModel {
~ int getHp()
~ List<ViewableEffect> getEffects()
~ ViewableItem getItem()
}

interface ITexturePack {
~ TextureRegion getTileTexture(ViewableTile)
~ TextureRegion getPlayerTexture(PlayerState,float)
~ TextureRegion getItemTexture(ViewableItem)
~ TextureRegion getEffectTexture(ViewableEffect)
~ TextureRegion getInventorySlot()
~ TextureRegion getHpTexture()
}

class Door1 {
+ {static} char KEY
+ <<Create>> Door1(World,EventBus,float,float)
+ <<Create>> Door1(World,EventBus,float,float,float,float)
}


interface Function4 {
~ R apply(A,B,C,D)
}

class EventPlayerAction {
- PlayerAction action
+ <<Create>> EventPlayerAction(PlayerAction)
+ PlayerAction action()
}


class TilePillarBottom {
+ {static} char KEY
+ <<Create>> TilePillarBottom(World,EventBus,float,float)
}


class PluginLoader {
~ {static} int CONSTANT_MODS
~ {static} Pattern classPattern
+ {static} List<String> listFiles(Class<?>,String,boolean)
+ {static} Stream<String> listClasses(Class<?>)
+ {static} Stream<String> listClasses(Class<?>,String)
+ {static} Stream<String> listClasses(Class<?>,String,boolean)
+ {static} Class<T> loadClass(String,Class<T>)
+ {static} Stream<Class<T>> loadClasses(Class<?>,Class<T>)
+ {static} Stream<Class<T>> loadClasses(Class<?>,String,Class<T>)
+ {static} Function<U,T> makeFactory(Class<T>,Class<U>)
+ {static} BiFunction<U,V,T> makeFactory(Class<T>,Class<U>,Class<V>)
+ {static} Function4<U,V,G,H,T> makeFactory(Class<T>,Class<U>,Class<V>,Class<G>,Class<H>)
+ {static} T getConstant(Class<?>,String,Class<T>)
}


class Barrel {
+ {static} char KEY
+ <<Create>> Barrel(World,EventBus,float,float)
}


class TileGrassCornerLeft1 {
+ {static} char KEY
+ <<Create>> TileGrassCornerLeft1(World,EventBus,float,float)
}




GameStateGettable <|-- ControllableGameModel
TileModel <|-- TileGrassCornerRight1
ContactableTiles <|.. DoorModel
TileModel <|-- DoorModel
ViewableEffect <|.. Effect
TileModel <|-- TileGroundLeft
ViewableItem <|.. ItemHP
ItemModel <|-- ItemHP
AbstractScreen <|-- PauseScreen
EventHandler <|.. Controller
InputAdapter <|-- Controller
TileModel <|-- TileFloatingGround
TileModel <|-- TileMiddle
AbstractScreen <|-- InfoScreen
TileModel <|-- TileGround
Stage <|-- Hud
ITexturePack <|.. TexturePack
TileHalf <|-- TileFloatingGroundLeftSlim
TileModel <|-- TileGrassCornerRight2
AbstractScreen <|-- MenuScreen
ItemModel <|-- ItemEnergy
DamageTileModel <|-- Saw
ContactableTiles <|.. DamageTileModel
TileModel <|-- DamageTileModel
Positionable <|-- ViewableTile
Sizeable <|-- ViewableTile
IHealth <|.. Health
AbstractScreen <|-- VictoryScreen
AbstractScreen <|-- LevelScreen
DoorModel <|-- Door2
ContactListener <|.. ContactListeners
TileModel <|-- TileGrassCornerLeft2
Effect <|-- EffectHpUp
Screen <|.. GameScreen
ControllablePlayerModel <|.. PlayerModel
ViewablePlayerModel <|.. PlayerModel
EventHandler <|.. PlayerModel
ContactListener <|.. PlayerModel
EventHandler <|.. GameView
Game <|-- GameView
TileModel <|-- TileHalf
TileModel <|-- TileGroundRight
ILevel <|.. Level
ViewableGameModel <|.. GameModel
ControllableGameModel <|.. GameModel
EventHandler <|.. GameModel
Effect <|-- EffectSpeedBoost
TileModel <|-- TilePillar
Actor <|-- Background
TileModel <|-- TileFloatingGroundRight
ViewableTile <|.. TileModel
Stepable <|.. TileModel
EventHandler <|.. TileModel
Stepable <|-- ControllableLevel
Screen <|.. AbstractScreen
AbstractScreen <|-- GameOverScreen
TileModel <|-- TileSideRight
Positionable <|-- ViewableItem
Sizeable <|-- ViewableItem
ViewableItem <|.. ItemModel
EventHandler <|.. ItemModel
ContactListener <|.. ItemModel
TileModel <|-- TileGroundSingle
Effect <|-- EffectJumpBoost
TileModel <|-- TileFloatingGroundLeft
TileModel <|-- TileBottom
Stepable <|-- ControllablePlayerModel
TileModel <|-- TileBottomRight
ItemModel <|-- ItemMushroom
TileHalf <|-- TileFloatingGroundRightSlim
ContactListener <|-- ContactableTiles
Event <|.. EventDispose
TileModel <|-- TileBottomLeft
TileModel <|-- TileFloatingGroundSingle
ViewableLevel <|-- ILevel
ControllableLevel <|-- ILevel
EventHandler <|-- ILevel
ContactListener <|-- ILevel
DamageTileModel <|-- Spike
GameStateGettable <|-- ViewableGameModel
TileHalf <|-- TileFloatingGroundSingleSlim
TileModel <|-- TileSideLeft
TileHalf <|-- TileFloatingGroundSlim
IAssetsManager <|.. AssetsManager
Sizeable <|-- ViewablePlayerModel
Positionable <|-- ViewablePlayerModel
PlayerStateGettable <|-- ViewablePlayerModel
DoorModel <|-- Door1
TileModel <|-- TilePillarBottom
TileModel <|-- Barrel
TileModel <|-- TileGrassCornerLeft1
@enduml